using Exceptions;
using Exceptions.Exceptions;
using System;
using System.Collections.Generic;

namespace Exceptions
{
    class Program
    {
        static void Main(string[] args)
        {
            //try
            //{
            //    int a = 9;
            //    int b = 0;

            //    var result = a / b;

            //    int[] arr = new int[5];

            //    arr[7] = 8;
            //}
            //catch (NullReferenceException ex)
            //{

            //    Console.WriteLine(ex.Message);
            //}
            //catch (DivideByZeroException ex)
            //{
            //    Console.WriteLine(ex.Message);
            //}
            //finally
            //{
            //    Console.WriteLine("Duzelin");
            //}

            //Divide(18, 2);


            //List<string> list = new List<string>() { "Cavidan,Orxan,Seid,Esqin" };
            //string searchText = "Cavidan";
            //FindName(list, searchText);
        }


        //public static void FindName(List<string> names, string name)
        //{
        //    try
        //    {
        //        if (names.Contains(name))
        //        {
        //            throw new FindNameException("Not found name");
        //        }
        //        Console.WriteLine("tapildi");
        //    }
        //    catch (Exception ex)
        //    {

        //        Console.WriteLine(ex.Message);
        //    }
        //}



        //public static void Divide(int num1 , int num2)
        //{
        //    try
        //    {
        //        if (num2 == 2)
        //        {
        //            throw new DivideException("num2 cant equal 2");
        //        }

        //        Console.WriteLine(num1/num2);
        //    }
        //    catch (Exception ex)
        //    {

        //        Console.WriteLine(ex.Message);
        //    }
            
        //}
    }
}
